#!/usr/bin/env python3
"""
Returns the path to the background music track.

The track at data/bg_music.mp3 is 100% synthetic — generated by ffmpeg
using layered sine waves in a pentatonic scale. It has no copyright,
no licence, no attribution required. Safe for YouTube monetisation.

No internet download, no third-party dependency.
"""
from pathlib import Path
import subprocess, sys

ROOT = Path(__file__).resolve().parent.parent
COMMITTED = ROOT / "data" / "bg_music.mp3"
FALLBACK   = Path("/tmp/azn_bg_music.mp3")


def fetch() -> Path:
    # Use the version committed to the repo — always available on Actions
    if COMMITTED.exists() and COMMITTED.stat().st_size > 100_000:
        print(f"Using committed background music ({COMMITTED.stat().st_size // 1024}KB)")
        return COMMITTED

    # Fallback: regenerate on the fly (takes ~10s)
    print("Generating background music via ffmpeg...")
    subprocess.run([
        "ffmpeg", "-y",
        "-f", "lavfi", "-i", "sine=frequency=174.6:duration=300",
        "-f", "lavfi", "-i", "sine=frequency=220.0:duration=300",
        "-f", "lavfi", "-i", "sine=frequency=261.6:duration=300",
        "-f", "lavfi", "-i", "sine=frequency=349.2:duration=300",
        "-filter_complex",
        "[0:a]volume=0.18,aecho=0.8:0.88:60:0.4[a0];"
        "[1:a]volume=0.14,aecho=0.8:0.88:80:0.4[a1];"
        "[2:a]volume=0.10,aecho=0.8:0.88:100:0.3[a2];"
        "[3:a]volume=0.08,aecho=0.8:0.88:120:0.3[a3];"
        "[a0][a1][a2][a3]amix=inputs=4:duration=longest,"
        "afade=t=in:st=0:d=4,afade=t=out:st=296:d=4,volume=0.6",
        "-ar", "44100", "-ac", "2", "-b:a", "128k",
        str(FALLBACK)
    ], capture_output=True, check=True)
    print("Background music generated.")
    return FALLBACK


if __name__ == "__main__":
    print(fetch())
