#!/usr/bin/env python3
"""
Assembles spec cards into finished videos.
  python3 src/render.py --format long    -> 1920x1080 long-form
  python3 src/render.py --format short   -> 1080x1920 Shorts

Features:
  - Product image in top-right corner (25% width)
  - Background music at -12dB (≈ 70% quieter than narration)
  - Hindi voiceover (generated by narrate.py)
  - English text on display cards
"""
import argparse, json, subprocess, shutil, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))
from cards import card, title_card
from fetch_image import fetch as fetch_image
from fetch_music import fetch as fetch_music

ROOT = Path(__file__).resolve().parent.parent


def dur_of(p: Path) -> float:
    r = subprocess.run(["ffprobe", "-v", "error", "-show_entries", "format=duration",
                        "-of", "csv=p=0", str(p)], capture_output=True, text=True)
    try:
        return float(r.stdout.strip())
    except ValueError:
        return 0.0


def composite_image(base_png: Path, product_img: Path, out_png: Path, size: tuple):
    """Overlay product image in top-right corner at 25% width."""
    W, H = size
    thumb_w = W // 4          # 25% of screen width
    thumb_h = thumb_w         # square crop
    x = W - thumb_w - int(W * 0.02)   # 2% margin from right
    y = int(H * 0.02)                  # 2% margin from top

    subprocess.run([
        "ffmpeg", "-y",
        "-i", str(base_png),
        "-i", str(product_img),
        "-filter_complex",
        f"[1:v]scale={thumb_w}:{thumb_h}:force_original_aspect_ratio=decrease,"
        f"pad={thumb_w}:{thumb_h}:(ow-iw)/2:(oh-ih)/2:color=black@0,"
        f"format=rgba,geq=r='r(X\\,Y)':a='if(gt(abs(X-{thumb_w//2})\\,{thumb_w//2}-4)*gt(abs(Y-{thumb_h//2})\\,{thumb_h//2}-4)\\,0\\,alpha(X\\,Y))'[thumb];"
        f"[0:v][thumb]overlay={x}:{y}:format=auto[out]",
        "-map", "[out]", "-frames:v", "1", str(out_png)
    ], check=True, capture_output=True)


def clip(png: Path, out: Path, seconds: float, size, audio: Path | None,
         music: Path | None, zoom=True):
    W, H = size
    vf = (f"scale={W*2}:{H*2},zoompan=z='min(zoom+0.0004,1.08)':"
          f"d={int(seconds*30)}:s={W}x{H}:fps=30" if zoom
          else f"scale={W}:{H},fps=30")

    cmd = ["ffmpeg", "-y", "-loop", "1", "-i", str(png)]

    # Audio mixing: narration + background music at -12dB (≈70% volume reduction)
    if audio and audio.exists() and music and music.exists():
        cmd += [
            "-i", str(audio),                    # input 1: narration
            "-i", str(music),                    # input 2: music
            "-filter_complex",
            f"[1:a]volume=1.0[narr];"            # narration at full volume
            f"[2:a]volume=0.30,aloop=loop=-1:size=2e+09[bg];"  # music at 30%
            f"[narr][bg]amix=inputs=2:duration=first:dropout_transition=2[audio]",
            "-map", "0:v", "-map", "[audio]",
            "-c:a", "aac", "-b:a", "192k", "-shortest"
        ]
    elif audio and audio.exists():
        cmd += ["-i", str(audio), "-c:a", "aac", "-b:a", "128k", "-shortest"]
    elif music and music.exists():
        cmd += [
            "-i", str(music),
            "-filter_complex", "[1:a]volume=0.30,aloop=loop=-1:size=2e+09[bg]",
            "-map", "0:v", "-map", "[bg]",
            "-c:a", "aac", "-b:a", "128k", "-shortest"
        ]
    else:
        cmd += ["-f", "lavfi", "-i", "anullsrc=r=44100:cl=stereo",
                "-c:a", "aac", "-shortest"]

    cmd += ["-t", f"{seconds}", "-vf", vf, "-c:v", "libx264",
            "-pix_fmt", "yuv420p", "-r", "30", "-preset", "veryfast", str(out)]
    subprocess.run(cmd, check=True, capture_output=True)


def concat(clips, out: Path):
    lst = out.parent / "_concat.txt"
    lst.write_text("\n".join(f"file '{c.resolve()}'" for c in clips))
    subprocess.run(["ffmpeg", "-y", "-f", "concat", "-safe", "0", "-i", str(lst),
                    "-c", "copy", str(out)], check=True, capture_output=True)
    lst.unlink()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--format", choices=["long", "short"], default="long")
    ap.add_argument("--seconds", type=float, default=55.0)
    ap.add_argument("--max-shorts", type=int, default=8,
                    help="Max number of Shorts to render (default: all)")
    a = ap.parse_args()

    d = sorted((ROOT / "out").glob("*/manifest.json"))[-1].parent
    ps = json.loads((d / "manifest.json").read_text())
    aud = d / "audio"
    work = d / f"_work_{a.format}"
    if work.exists(): shutil.rmtree(work)
    work.mkdir(parents=True)

    size = (1920, 1080) if a.format == "long" else (1080, 1920)
    top = max(p["discount"] for p in ps)
    head = f"Up to {top}% off" if top >= 40 else "Best value picks"

    # Fetch background music once
    print("Fetching background music...")
    music = fetch_music()

    if a.format == "long":
        clips = []
        t = title_card(head, f"{len(ps)} picks - links in description", size)
        tp = work / "000.png"; t.save(tp)
        c0 = work / "000.mp4"
        clip(tp, c0, 6, size, None, music, zoom=False)
        clips.append(c0)

        for i, p in enumerate(ps, 1):
            print(f"Rendering card {i}/{len(ps)}: {p['name']}")
            # Base card
            base_png = work / f"{i:03d}_base.png"
            card(p, i, len(ps), size).save(base_png)

            # Try fetching product image
            final_png = work / f"{i:03d}.png"
            prod_img = fetch_image(p["asin"])
            if prod_img:
                try:
                    composite_image(base_png, prod_img, final_png, size)
                    print(f"  ✓ Product image added for {p['asin']}")
                except Exception as e:
                    print(f"  ✗ Image composite failed: {e}, using base card")
                    shutil.copy(base_png, final_png)
            else:
                print(f"  ✗ No image for {p['asin']}, using base card")
                shutil.copy(base_png, final_png)

            av = aud / f"{i:02d}.wav"
            secs = dur_of(av) + 1.0 if av.exists() else a.seconds
            mp4 = work / f"{i:03d}.mp4"
            clip(final_png, mp4, secs, size, av if av.exists() else None, music)
            clips.append(mp4)

        out = d / "long.mp4"
        concat(clips, out)
        print(f"\n✅ long-form -> {out}  ({dur_of(out):.0f}s)")

    else:
        max_s = getattr(a, 'max_shorts', len(ps))
        to_render = ps[:max_s]
        for i, p in enumerate(to_render, 1):
            print(f"Rendering short {i}/{len(to_render)}: {p['name']}")
            base_png = work / f"s{i:03d}_base.png"
            card(p, i, len(ps), size).save(base_png)

            final_png = work / f"s{i:03d}.png"
            prod_img = fetch_image(p["asin"])
            if prod_img:
                try:
                    composite_image(base_png, prod_img, final_png, size)
                except Exception:
                    shutil.copy(base_png, final_png)
            else:
                shutil.copy(base_png, final_png)

            av = aud / f"short_{i:02d}.wav"
            secs = dur_of(av) + 0.8 if av.exists() else 30.0
            out_f = d / f"short_{i:02d}.mp4"
            clip(final_png, out_f, min(secs, 59), size,
                 av if av.exists() else None, music)
            print(f"  -> {out_f}  ({secs:.0f}s)")


if __name__ == "__main__":
    main()
